{% set name = "pysm3" %}
{% set version = "3.4.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e491922ed3cc3de98f8ba273f6b1cfdfd5fadad8a359e8939a39cf0cd29c2397

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - astropy-base
    - hatchling
    - hatch-vcs
    - healpy >=1.18.1
    - h5py
    - numba
    - numpy >=1.21
    - scipy >=1.10
    - toml
  run:
    - python >={{ python_min }}
    - astropy-base
    - healpy >=1.18.1
    - h5py
    - numba
    - numpy >=1.21
    - scipy >=1.10
    - toml

test:
  imports:
    - pysm3
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-astropy

about:
  home: https://github.com/galsci/pysm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Sky Model for Microwave and Submm experiments

  # The remaining entries in this section are optional, but recommended.
  doc_url: https://pysm3.readthedocs.io/

extra:
  recipe-maintainers:
    - zonca
